### ISSUE TITLE
callouts=None case not handled in AWSCloudWatchLogs

### ISSUE THREAD

**Issue by anentropic** [kitchenita/python-logger-cloudwatch-structlog#1]
https://github.com/kitchenita/python-logger-cloudwatch-structlog/blob/63f24773da83eb3617f1b964275525b83cf8ceb4/logger_cloudwatch_structlog/custom_processors.py#L24-L33

when `callouts=None` the attempt to do `callouts[0]` raises `TypeError` rather than `IndexError`... so that exception is not caught and the logging fails

**Comment by facundolucianna** [comment]
Good catch! Thanks :)

I have already fixed the issue; the releases v0.1.1 and v0.0.5 address this problem.

Thank you so much for reporting this issue, and I apologize for the late response :S.
